version: '2'
services:

  calvin-app:
    image: calvinapp
    build: 
      context: ./
      dockerfile: DockerFile
    network_mode: host
    restart: on-failure
    volumes:
      - ./dockerScripts:/temp/scripts
    ports:
      - 3000:3000
    depends_on:
      - calvin-cassandra
    entrypoint:
      -  /temp/scripts/wait-for-service.sh
      - '0.0.0.0'
      - '9042'
      - 'npm start'

  calvin-cassandra:
    image: cassandra:latest
    network_mode: host
    restart: on-failure
    volumes:
      - ./data:/var/lib/cassandra
    expose:
      - 9042          